version: '2'

services:
  template:
    build:
      context: .
      dockerfile: toasts/template/Dockerfile
    volumes:
      - ./basement/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./basement/scripts:/scripts
      - ./toasts/template/:/var/www/repo
    env_file:
      - ./toasts/template/.env
    ports:
      - 4000:3000
    restart: always
  example:
    build:
      context: .
      dockerfile: toasts/example/Dockerfile
    volumes:
      - ./basement/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./basement/scripts:/scripts
      - ./toasts/example:/var/www/repo
    env_file:
      - ./toasts/example/.env
    ports:
      - 4001:3000
    restart: always
  hackathon:
    build:
      context: .
      dockerfile: toasts/hackathon/Dockerfile
    volumes:
      - ./basement/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./basement/scripts:/scripts
      - ./toasts/hackathon:/var/www/repo
    env_file:
      - ./toasts/hackathon/.env
    ports:
      - 3000:3000
    restart: always
